# Generated by Django 3.1 on 2020-09-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200908_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWork',
        ),
    ]
