# Generated by Django 3.1 on 2020-09-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200909_2055'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Work'),
        ),
    ]
