# Generated by Django 3.1 on 2020-08-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.CharField(choices=[('R', 'rush'), ('U', 'usual'), ('NR', 'not rush')], max_length=2, verbose_name='')),
                ('type', models.CharField(choices=[('SE', 'shop equipment'), ('W', 'worldwide')], max_length=2, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Shop name')),
                ('city', models.CharField(max_length=128, verbose_name='')),
                ('street', models.CharField(max_length=128, verbose_name='')),
                ('house', models.IntegerField(verbose_name='')),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='')),
                ('works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.work', verbose_name='')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
